Implementation of OWL converter. Still error Exception in thread "main" java.lang.NoClassDefFoundError: aterm/ATerm 	at openDataWrapper.OWLConverter.run(OWLConverter.java:67) 	at openDataWrapper.Principale.owl(Principale.java:158) 	at openDataWrapper.Principale.main(Principale.java:136) Caused by: java.lang.ClassNotFoundException: aterm.ATerm 	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) 	at java.security.AccessController.doPrivileged(Native Method) 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 	... 3 more